---
- name: Docker Hosts
  hosts: docker-hosts
  become: true
  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      ansible.builtin.raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-apt || apt install -y python3-minimal python3-apt)
      changed_when: false
    - name: Gathering Facts
      ansible.builtin.setup:  # aka gather_facts
  roles:
    - role: waja.dockerconfig
    - role: geerlingguy.docker
    - role: darkwizard242.lazydocker
    - role: waja.dockertools
