---
- name: Converge
  hosts: all
  become: true
  vars:
    docker_service_manage: false

  roles:
    - role: waja.dockerconfig
    - role: geerlingguy.docker
      tags:
        - molecule-idempotence-notest
    - role: darkwizard242.lazydocker
    - role: waja.dockertools
